create or replace TABLE LOAD.GOOGLE_DRIVE.EXPENSES (
	_FILE VARCHAR(256) NOT NULL,
	_LINE NUMBER(38,0) NOT NULL,
	_MODIFIED TIMESTAMP_TZ(9),
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	DATE DATE,
	EXPENSE_TYPE VARCHAR(256),
	EXPENSE_AMOUNT VARCHAR(256),
	primary key (_FILE, _LINE)
);