create or replace TABLE LOAD.GOOGLE_DRIVE.HR_QUITS (
	_FILE VARCHAR(256) NOT NULL,
	_LINE NUMBER(38,0) NOT NULL,
	_MODIFIED TIMESTAMP_TZ(9),
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	EMPLOYEE_ID NUMBER(38,0),
	QUIT_DATE DATE,
	primary key (_FILE, _LINE)
);