create or replace TABLE LOAD.GOOGLE_DRIVE.HR_JOINS (
	_FILE VARCHAR(256) NOT NULL,
	_LINE NUMBER(38,0) NOT NULL,
	_MODIFIED TIMESTAMP_TZ(9),
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	EMPLOYEE_ID NUMBER(38,0),
	HIRE_DATE VARCHAR(256),
	NAME VARCHAR(256),
	CITY VARCHAR(256),
	ADDRESS VARCHAR(256),
	TITLE VARCHAR(256),
	ANNUAL_SALARY NUMBER(38,0),
	primary key (_FILE, _LINE)
);