create or replace TABLE LOAD.GOOGLE_DRIVE.RETURNS (
	_FILE VARCHAR(256) NOT NULL,
	_LINE NUMBER(38,0) NOT NULL,
	_MODIFIED TIMESTAMP_TZ(9),
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	RETURNED_AT DATE,
	ORDER_ID VARCHAR(256),
	IS_REFUNDED VARCHAR(256),
	primary key (_FILE, _LINE)
);