create or replace TABLE LOAD.RESOURCES_2_WEB_SCHEMA.ORDERS (
	_FIVETRAN_ID VARCHAR(256) NOT NULL,
	STATE VARCHAR(256),
	SESSION_ID VARCHAR(256),
	SHIPPING_COST VARCHAR(256),
	PAYMENT_METHOD VARCHAR(256),
	PHONE VARCHAR(256),
	TAX_RATE FLOAT,
	CLIENT_NAME VARCHAR(256),
	ORDER_AT TIMESTAMP_NTZ(9),
	ORDER_ID VARCHAR(256),
	SHIPPING_ADDRESS VARCHAR(256),
	PAYMENT_INFO VARCHAR(256),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (_FIVETRAN_ID)
);