create or replace TABLE LOAD.RESOURCES_2_WEB_SCHEMA.SESSIONS (
	_FIVETRAN_ID VARCHAR(256) NOT NULL,
	SESSION_ID VARCHAR(256),
	SESSION_AT TIMESTAMP_NTZ(9),
	CLIENT_ID NUMBER(38,0),
	IP VARCHAR(256),
	OS VARCHAR(256),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (_FIVETRAN_ID)
);