create or replace TABLE LOAD.RESOURCES_2_WEB_SCHEMA.ITEM_VIEWS (
	_FIVETRAN_ID VARCHAR(256) NOT NULL,
	ITEM_NAME VARCHAR(256),
	SESSION_ID VARCHAR(256),
	REMOVE_FROM_CART_QUANTITY NUMBER(38,0),
	ADD_TO_CART_QUANTITY NUMBER(38,0),
	PRICE_PER_UNIT FLOAT,
	ITEM_VIEW_AT TIMESTAMP_NTZ(9),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (_FIVETRAN_ID)
);