create or replace TABLE LOAD.RESOURCES_2_WEB_SCHEMA.PAGE_VIEWS (
	_FIVETRAN_ID VARCHAR(256) NOT NULL,
	SESSION_ID VARCHAR(256),
	VIEW_AT TIMESTAMP_NTZ(9),
	PAGE_NAME VARCHAR(256),
	_FIVETRAN_DELETED BOOLEAN,
	_FIVETRAN_SYNCED TIMESTAMP_TZ(9),
	primary key (_FIVETRAN_ID)
);