select
    _FIVETRAN_ID,
	ITEM_NAME,
	SESSION_ID,
	REMOVE_FROM_CART_QUANTITY,
	ADD_TO_CART_QUANTITY,
    CASE 
        WHEN SUBSTR(PRICE_PER_UNIT, 1, 1) = '$' THEN REPLACE(PRICE_PER_UNIT, '$ ', '') 
        ELSE PRICE_PER_UNIT 
    END AS PRICE_PER_UNIT
	ITEM_VIEW_AT,
	_FIVETRAN_DELETED,
	_FIVETRAN_SYNCED

FROM {{ source('Snowflake', 'ITEM_VIEWS') }}