select
	_FIVETRAN_ID,
	SESSION_ID,
	SESSION_AT AS SESSION_AT_TS,
	CLIENT_ID NUMBER,
	IP,
	OS,
	_FIVETRAN_DELETED,
	_FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,

FROM {{ source('Snowflake', 'SESSIONS') }}