SELECT 
    _FILE,
	_LINE,
	_MODIFIED AS _MODIFIED_TS,
	_FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS,
	EMPLOYEE_ID,
	CAST(REPLACE(hire_date, 'day ', '') AS DATE) as hire_date,
	NAME,
	CITY,
	ADDRESS,
	TITLE,
	CAST(ANNUAL_SALARY AS NUMERIC) as ANNUAL_SALARY,
FROM {{ source('google_drive', 'HR_JOINS') }}