name: Upload Python Package to PyPI when a Release is Created

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/st-gsheets-connection
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.bump.outputs.new_tag }}
          release_name: ${{ steps.bump.outputs.new_tag }}
          body: |
            Changes in this Release
            - Rebuilt Docker image and published to DockerHub with new tag
          draft: false
          prerelease: false
      - name: Build package
        run: |
          python setup.py install sdist bdist_wheel
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
