version: 2

sources:
  - name: google_drive
    database: LOAD
    schema: GOOGLE_DRIVE
    tables:
      - name: EXPENSES
        freshness:
          warn_after: {count: 1, period: day}
        loaded_at_field: fivetran_synced
      - name: HR_JOINS
        freshness:
          warn_after: {count: 1, period: day}
        loaded_at_field: fivetran_synced
      - name: HR_QUITS
        freshness:
          warn_after: {count: 1, period: day}
        loaded_at_field: fivetran_synced
      - name: RETURNS
        freshness:
          warn_after: {count: 1, period: day}
        loaded_at_field: fivetran_synced

  - name: Snowflake
    database: LOAD
    schema: RESOURCES_2_WEB_SCHEMA
    tables:
      - name: ITEM_VIEWS
        freshness:
          warn_after: {count: 1, period: day}
        loaded_at_field: fivetran_synced
      - name: ORDERS
        freshness:
          warn_after: {count: 1, period: day}
        loaded_at_field: fivetran_synced
      - name: PAGE_VIEWS
        freshness:
          warn_after: {count: 1, period: day}
      - name: SESSIONS
        freshness:
          warn_after: {count: 1, period: day}
